
[general]

	[general.battle]

		[general.battle.ares_fragment]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 10
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 25
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 35
			#Range: > 0
			base_roll = 10
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Range: 0.0 ~ 1.7976931348623157E308
			durability_reduction_scaling = 1.3
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:berserk", "uniquee:alchemistsgrace", "uniquee:ender_mending", "minecraft:mending"]
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Range: 0.0 ~ 1.7976931348623157E308
			durability_distribution = 0.6
			#If the Enchantment is a Treasure
			treasure = true
			#Range: 0.0 ~ 1.7976931348623157E308
			armor_percentage = 0.6
			#Range: 0.0 ~ 1.7976931348623157E308
			base_roll_multiplier = 1.0
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Range: > 0
			durability_anti_scaling = 11
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"

		[general.battle.snare]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 75
			#Range: > 0
			duration_base = 30
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 20
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 5
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 3
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#Range: > 0
			duration_level = 50
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "UNCOMMON"

		[general.battle.granis_soul]
			#Range: > 0
			bleed_duration_level = 20
			#Range: > 0
			bleed_range_level = 1
			#Range: > 0
			bleed_duration_base = 200
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 20
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 40
			#Range: 0.0 ~ 1.7976931348623157E308
			dash_speed = 9.0
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 10
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 5
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Range: > 0
			dash_duration = 50
			#If the Enchantment is a Treasure
			treasure = true
			#Range: > 0
			bleed_range_base = 3
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"

		[general.battle.ares_grace]
			#Range: 0.0 ~ 1.7976931348623157E308
			damage = 1.0
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 75
			#Range: 0.0 ~ 1.7976931348623157E308
			durability = 1.0
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 2
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 8
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 3
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquebattle:ares_fragment"]
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"

		[general.battle.artemis_soul]
			#Range: 0.0 ~ 1.7976931348623157E308
			perm_soul_scale = 1.0
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 45
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 15
			#Range: 0.0 ~ 1.7976931348623157E308
			temp_soul_scale = 1.0
			#Range: > 0
			base_limit = 625
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 60
			valid_mobs = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:shulker", "minecraft:elder_guardian", "minecraft:ravager", "minecraft:evoker"]
			#Range: 0.0 ~ 1.7976931348623157E308
			reap_scale = 1.0
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 7
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Range: 0.0 ~ 1.7976931348623157E308
			base_limit_scale = 1.0
			#Range: > 0
			base_limit_expansion = 625
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "VERY_RARE"
			#Range: 0.0 ~ 1.7976931348623157E308
			drop_scale = 1.0

		[general.battle.celestial_blessing]
			#Range: 0.0 ~ 1.7976931348623157E308
			speed_bonus_level = 0.04
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 15
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 14
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#Range: 0.0 ~ 1.7976931348623157E308
			speed_bonus_base = 0.08
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 5
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 3
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:climate_tranquility"]
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "UNCOMMON"

		[general.battle.ifrits_judgement]
			#Range: > 0
			fire_hits = 4
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 40
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Range: > 0
			burn_duration_base = 30
			#Range: 0.0 ~ 1.7976931348623157E308
			lava_damage_level = 0.1
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 2
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#Range: 0.0 ~ 1.7976931348623157E308
			fire_damage_base = 0.4
			#If the Enchantment is a Treasure
			treasure = false
			#Range: > 0
			burn_duration_level = 10
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Range: 0.0 ~ 1.7976931348623157E308
			fire_damage_level = 0.1
			#Range: 0.0 ~ 1.7976931348623157E308
			lava_damage_base = 0.4
			#Range: > 0
			lava_hits = 6
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"

		[general.battle.golem_soul]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 50
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 16
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#Range: 0.0 ~ 1.7976931348623157E308
			knockback = 0.25
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 3
			#Range: 0.0 ~ 1.7976931348623157E308
			speed = 0.05
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"

		[general.battle.lunatic_despair]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 40
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage = 0.2
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 2
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "VERY_RARE"

		[general.battle.ifrits_blessing]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 60
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 12
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 2
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage_level = 0.6
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 5
			#Enchantments that are not compatible with this Enchantment
			incompats = ["uniquee:berserk"]
			#Range: 0.0 ~ 1.7976931348623157E308
			bonus_damage_base = 0.2
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "COMMON"

	[general.base]

		[general.base.wars_odium]
			#Range: 0.0 ~ 1.7976931348623157E308
			health_buff_base = 0.0
			#Range: 0.0 ~ 1.7976931348623157E308
			hit_level = 0.02
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 40
			#Range: 0.0 ~ 1.7976931348623157E308
			multiplier = 1.0
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			blacklist = []
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 10
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 2
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = true
			#If the Enchantment is a Treasure
			treasure = false
			#Range: 0.0 ~ 1.7976931348623157E308
			health_buff_level = 1.0
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Range: 0.0 ~ 1.7976931348623157E308
			hit_base = 0.05
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "VERY_RARE"

		[general.base.deep_wounds]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 20
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 28
			#Range: 0.0 ~ 1.7976931348623157E308
			bleed_scale = 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			scale = 1.0
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#Range: > 0
			duration = 24
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"

		[general.base.fury]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 50
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 20
			#Range: 0.0 ~ 1.7976931348623157E308
			attack_speed_scale = 1.0
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#Range: 0.0 ~ 1.7976931348623157E308
			drop_chance_level = 0.03
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 3
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#Range: 0.0 ~ 1.7976931348623157E308
			drop_chance_base = 0.01
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = true
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "RARE"

		[general.base.streakers_will]
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 15
			#Range: 0.0 ~ 1.7976931348623157E308
			chance_level = 0.15
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 12
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 4
			#Range: 0.0 ~ 1.7976931348623157E308
			loss = 11.25
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = false
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#Range: 0.0 ~ 1.7976931348623157E308
			chance_base = 0.1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "UNCOMMON"

		[general.base.iron_bird]
			#Range: 0.0 ~ 1.7976931348623157E308
			armor_level = 1.0
			#Range: 0.0 ~ 1.7976931348623157E308
			armor_base = 3.0
			#The Additional Upper Range of Required Levels
			#Range: > 0
			cost_limit = 75
			#Minimum Level for Enchanting
			#Range: > 0
			base_cost = 10
			#Allows to add custom incompatible Items
			incompatible_items = []
			#Allows to add custom compatible Items
			compatible_items = []
			#If the Enchantment is Obtainable
			enabled = true
			#Increase of levels per Enchantment Level
			#Range: > 0
			per_level_cost = 5
			#Hard Limit of where the Enchantment will be capped even if the level is higher
			#Range: > 0
			hard_cap = 100
			#Maximum Enchantment Level
			#Range: > 0
			max_level = 4
			#Enchantments that are not compatible with this Enchantment
			incompats = []
			#If the Enchantment is Tradeable by Villagers
			tradeable = false
			#If the Enchantment is a Treasure
			treasure = false
			#Range: 0.0 ~ 1.7976931348623157E308
			toughness = 1.0
			#Minimum Enchantment Level
			#Range: > 0
			min_level = 1
			#If the Enchantment has any effect
			activated = true
			#Rarity of the Enchantment
			#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
			rarity = "VERY_RARE"

